### PR TITLE
Allow namespaces for "wait-for" topics

### PR DESCRIPTION
**Pull request by Jntzko**
The controller are waiting for the /calibrated topic, the leading "/" does not allow to run the hand in a namespace.

### CODE REVIEW

**Comment by guihomework** [comment]
We are running our right and left hands in namespaces (two realtime loops in rh and lh namespaces) and never noticed a problem. 
Do you mean that the /calibrated parameter is shared by the two hands or do you mean that the hand is never calibrating ?
What is the problem ? I remember we had problem with the hand never calibrating but this came from another race condition issue which was fixed see  https://github.com/shadow-robot/sr_core/issues/34#issuecomment-150694123 

I am interested in this, as your changes might actually change the behaviour when starting our hands

**Comment by Jntzko** [comment]
The problem occurred as our tactile controller didn't started because it was waiting for the /calibrated topic and not for the /namespace/calibrated topic. The same happens also at least for the trajectory controller.

We mounted our shadow hand on another robot which also publishes on the /calibrated topic, that way, the controllers are started when the robot finished calibrating and not when the shadow hand finished.
For your setup, this should be similar, when one hand finished calibrating and publishes on the /calibrated topic, the other hand also assumes it is calibrated. Still in our case, the node who publishes the calibrated message, publishes it in the namespace where no one is listening.

Are you sure you run your hands in namespaces and not only with the hand_id prefix?

**Comment by guihomework** [comment]
@Jntzko thanks for the clarification. We have tactile controllers but we disabled the trajectory controllers.
It sounds possible that the left hand thinks it is calibrated when the right hand already publishes on /calibrated. I will double check this today and give feedback here.
I will also test your changes to see if it affects us.

**Comment by guihomework** [comment]
@Jntzko seems like I don't have this wait-for-calib yet in my branch, and I did not notice it was added to the main kinetic-devel branch because this PR https://github.com/shadow-robot/sr-ros-interface-ethercat/pull/179 is not closed but the patch is already merged here https://github.com/shadow-robot/sr-ros-interface-ethercat/commit/92530e44f50208e6d951ddb87970bfe7b6711c8a
which explains why my tactile controllers are fine (see further for the actual test of your patch).

@toliver why are PR recreated and merged instead of using the user provided PR ? this could help trace things more easily. 

If I add the patch merged by shadow I can reproduce your problem 
```
[WARN] [1546625506.959726]: Controller Spawner hasn't heard anything from its "wait for" topic (/calibrated)
```
So I **confirm** this bug and **approve** your fix in this PR for the **sr_tactile_controller**
but regarding the fix for the **sr_edc_*_controllers** I **cannot confirm** but think it is the same. 
Indeed, on our side, we decided to use our own spawner and store it in sr_ethercat_hand_config/launch/controllers/sr_edc_mixed_position_velocity_controllers.launch
where we indeed have a fix for this calibrated issue in a namespace using the hand_id

```
 <node name="default_loaded_controllers_spawner"
          pkg="controller_manager" type="spawner" output="screen"
          args="--wait-for=/$(arg hand_id)/calibrated --stopped sh_$(arg hand_id)_ffj0_mixed_position_velocity_controller sh_$(arg hand_id)_ffj3_mixed_position_velocity_controller sh_$(arg hand_id)_ffj4_mixed_position_velocity_controller sh_$(arg hand_id)_mfj0_mixed_position_velocity_controller sh_$(arg hand_id)_mfj3_mixed_position_velocity_controller sh_$(arg hand_id)_mfj4_mixed_position_velocity_controller sh_$(arg hand_id)_rfj0_mixed_position_velocity_controller sh_$(arg hand_id)_rfj3_mixed_position_velocity_controller sh_$(arg hand_id)_rfj4_mixed_position_velocity_controller sh_$(arg hand_id)_lfj0_mixed_position_velocity_controller sh_$(arg hand_id)_lfj3_mixed_position_velocity_controller sh_$(arg hand_id)_lfj4_mixed_position_velocity_controller sh_$(arg hand_id)_lfj5_mixed_position_velocity_controller sh_$(arg hand_id)_thj1_mixed_position_velocity_controller sh_$(arg hand_id)_thj2_mixed_position_velocity_controller sh_$(arg hand_id)_thj3_mixed_position_velocity_controller sh_$(arg hand_id)_thj4_mixed_position_velocity_controller sh_$(arg hand_id)_thj5_mixed_position_velocity_controller sh_$(arg hand_id)_wrj1_mixed_position_velocity_controller sh_$(arg hand_id)_wrj2_mixed_position_velocity_controller" />
```
Applying your patch and dropping the hand_id and the front slash would probably work as my _default_loaded_controllers_spawner_ is started in a namespace, but I will keep it as is now. 

Your fix is more generic in the sense that it does not depend on the hand_id but I am not sure choosing a namespace called myrighthand instead of rh would work, a lot of things are not cleanly separated/independant between namespace, hand_id, joint_prefix link_prefix etc... see https://github.com/shadow-robot/sr-ros-interface-ethercat/issues/56 but I closed this issue as I managed to get something working but changing for a fully clean solution is quite a nightmare that I did not want to tackle. 

For future reference, when I launch my right hand driver I have this
```
TOPICS (useful abstract)
/rh/calibrated   

rostopic info /rh/calibrated 
Publishers: 
 * /rh/calibrate_sr_edc 

Subscribers: 
 * /rh/default_loaded_controllers_spawner 
  
rostopic echo /rh/calibrated 
data: True

PARAMS (useful abstract)
 /hand/joint_prefix/SERIALNUM: rh_
 /hand/mapping/SERIALNUM: rh
 /rh/rh_hand_trajectory_controller/allow_partial_joints_goal: True
 /rh/realtime_loop/rh/default_control_mode: FORCE
 /rh/realtime_loop/use_ns: False
 /rh/sr_rh_tactile_sensor_controller/prefix: rh
 /rh/sr_rh_tactile_sensor_controller/publish_rate: 100
 /rh/sr_rh_tactile_sensor_controller/type: sr_tactile_sensor...

NODES (useful abstract)
  /rh/
    calibrate_sr_edc (sr_utilities/calibrate_hand_finder.py)
    default_loaded_controllers_spawner (controller_manager/spawner)
    hand_trajectory_controller_spawner (controller_manager/spawner)
    joint_state_controller_spawner (controller_manager/spawner)
    realtime_loop (ros_ethercat_loop/ros_ethercat_loop)
    robot_state_publisher (robot_state_publisher/state_publisher)
    sr_rh_tactile_sensor_controller_spawner (controller_manager/spawner)

[INFO] [1546623079.191142]: Controller Spawner: Loaded controllers: rh_hand_trajectory_controller
Launched: cal_sh_rh_ffj0, cal_sh_rh_ffj3, cal_sh_rh_ffj4, cal_sh_rh_mfj0, cal_sh_rh_mfj3, cal_sh_rh_mfj4, cal_sh_rh_rfj0, cal_sh_rh_rfj3, cal_sh_rh_rfj4, cal_sh_rh_lfj0, cal_sh_rh_lfj3, cal_sh_rh_lfj4, cal_sh_rh_lfj5, cal_sh_rh_thj1, cal_sh_
rh_thj2, cal_sh_rh_thj3, cal_sh_rh_thj4, cal_sh_rh_thj5, cal_sh_rh_wrj1, cal_sh_rh_wrj2
Waiting for: cal_sh_rh_ffj0, cal_sh_rh_ffj3, cal_sh_rh_ffj4, cal_sh_rh_mfj0, cal_sh_rh_mfj3, cal_sh_rh_mfj4, cal_sh_rh_rfj0, cal_sh_rh_rfj3, cal_sh_rh_rfj4, cal_sh_rh_lfj0, cal_sh_rh_lfj3, cal_sh_rh_lfj4, cal_sh_rh_lfj5, cal_sh_rh_thj1, cal_
sh_rh_thj2, cal_sh_rh_thj3, cal_sh_rh_thj4, cal_sh_rh_thj5, cal_sh_rh_wrj1, cal_sh_rh_wrj2
Calibration complete
```

**Comment by toliver** [comment]
@guihomework the reason we have a separate PR is that the PR is to backport the change to `indigo-devel`. The change was merged into `kinetic-devel`.

The fix proposed here looks like a good solution. We will have to test it before it gets merged. @AndriyPt  can confirm that.

About prefixing with the hand prefix it could be a good idea, but we need to check how does that play with the way we do bimanual currently (with both hands running in the same ROS node.

**Comment by guihomework** [comment]
@toliver thanks for the explanation. However, if things are merged now, would be nice to close the other PR pointing to the actual merge point or the new PR.

with the single loop running a bimanual hand system, i don't think my solution can work as there is currently only a single calibration controller started if I understand the sr_edc_bimanual correctly.

I don't mind the current PR if this solves every case. I will wait for this PR to be closed to merge the changes in our branch.

**Comment by v4hn** [comment]
ping @toliver @AndriyPt 

absolute namespaces should be avoided in compositional robot setups.
As the hand is (almost always) mounted on an arm, this applies here.

It would be nice to see this merged.

Thanks for cross-validating @guihomework :+1:

**Comment by AndriyPt** [comment]
Fully agree on that @v4hn :)
We will perform quick internal testing most likely till the end of this week.
Based on that testing we will be able to merge this PR.

**Pull request merged**
